version: "3.9"

services:
  postgres:
    image: postgres:13.2
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres-db-volume:/var/lib/postgres/data

  app:
    build:
      dockerfile: ./service/Dockerfile
    container_name: seattle_houses
    restart: always
    environment:
      DB_CONN: ${DB_CONN}
    ports:
      - "8000:8000"
    depends_on:
      - postgres
